stages:
  parse:
    cmd: python src/nlp_index/data/parse.py
    deps:
      - src/nlp_index/data/parse.py
      - data/raw/chat_export.json
    outs:
      - data/prepared/messages.csv
  index:
    cmd: python src/nlp_index/index.py
    deps:
      - data/prepared/messages.csv
      - src/nlp_index/index.py
    outs:
      - data/prepared/index
